server:
  port: 8090

spring:
  application:
    name: sc-generator
  datasource:
    url: jdbc:h2:./sc;MODE=MySQL
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: H2
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  http:
    multipart:
      max-file-size: 20MB
  jackson:
    default-property-inclusion: non_null

zuul:
  servlet-path: /proxy

security:
  user:
    name: anonymous
    password: anonymous
  basic:
    authorize-mode: none